const FilmActionTypes = {
    GET_ALL : 'GET_ALL',
    GET_FILM_BY_ID: 'GET_FILM_BY_ID',
    GET_PROJECTIONS_BY_FILM_ID: 'GET_PROJECTIONS_BY_FILM_ID',
    GET_AVAILABLE_SEATS_FOR_PROJECTION: 'GET_AVAILABLE_SEATS_FOR_PROJECTION',

    REMOVE_FILMS: 'REMOVE_FILMS',
    REMOVE_FILM: 'REMOVE_FILM',
};

export default FilmActionTypes;