const FilmActionTypes = {
    GET_ALL : 'GET_ALL',
    GET_FILM_BY_ID: 'GET_FILM_BY_ID',
    GET_PROJECTIONS_BY_FILM_ID: 'GET_PROJECTIONS_BY_FILM_ID',
    GEt_AVAILABLE_SEATS_FOR_PROJECTION: 'GEt_AVAILABLE_SEATS_FOR_PROJECTION',

    REMOVE_FILM: 'REMOVE_FILM'
};

export default FilmActionTypes;