const HallActionTypes = {
    GET_ALL_HALLS: 'GET_ALL_HALLS',
    GET_PROJECTION_BY_HALL_ID: 'GET_PROJECTION_BY_HALL_ID',

    CLEAR_ALL_HALLS: 'CLEAR_ALL_HALLS',
    CLEAR_PROJECTIONS_FOR_HALL: 'CLEAR_PROJECTIONS_FOR_HALL'
};

export default HallActionTypes;